package main

import (
	_ "embed"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

//go:embed assets/claude/commands/start-task.md
var claudeStartTaskCommand string

const claudeStartTaskFile = "start-task.md"

func installCommand(args []string) error {
	if len(args) == 0 {
		fmt.Println("Usage: domux install tmux|claude|codex [--apply] | caffeinate [--full]")
		fmt.Println()
		fmt.Println("tmux/claude/codex: preview-only by default. Pass --apply to write.")
		fmt.Println("caffeinate: registers partial mode immediately. Pass --full for lid-close prevention (requires sudo).")
		return nil
	}
	switch args[0] {
	case "tmux":
		return installTmux(args[1:])
	case "claude":
		return installClaude(args[1:])
	case "codex":
		return installCodex(args[1:])
	case "caffeinate":
		return installCaffeinate(args[1:])
	default:
		return fmt.Errorf("unknown install target %q", args[0])
	}
}

func installTmux(args []string) error {
	fs := flag.NewFlagSet("install tmux", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	apply := fs.Bool("apply", false, "write ~/.config/domux/domux.tmux")
	if err := fs.Parse(args); err != nil {
		return err
	}
	path, err := domuxConfigDir("domux.tmux")
	if err != nil {
		return err
	}
	content := generatedTmuxConfig()
	if !*apply {
		fmt.Printf("Would write %s:\n\n%s\n", path, content)
		fmt.Println("Then source it from tmux with:")
		fmt.Println("  source-file ~/.config/domux/domux.tmux")
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("cannot create %s: %w", filepath.Dir(path), err)
	}
	if err := backupIfExists(path); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("cannot write %s: %w", path, err)
	}
	fmt.Printf("wrote %s\n", path)
	fmt.Println("Add this to ~/.tmux.conf when ready:")
	fmt.Println("  source-file ~/.config/domux/domux.tmux")
	return nil
}

func generatedTmuxConfig() string {
	return strings.TrimSpace(`
# Generated by domux. Source this file from ~/.tmux.conf.

bind-key s display-popup -E -w 60% -h 50% "$HOME/bin/domux sessions"
bind-key t display-popup -E -w 60% -h 50% -d "#{pane_current_path}" "$HOME/bin/domux"
bind-key u display-popup -E -w 50% -h 30% "$HOME/bin/domux commands"

bind-key i run-shell '$HOME/bin/domux ai-state --session "#{session_name}" --pane "#{window_index}_#{pane_index}" toggle'
bind-key v run-shell '$HOME/bin/domux server --session "#{session_name}" toggle'
bind-key f run-shell '$HOME/bin/domux clear-state' \; display-message "domux session state cleared"

bind-key N command-prompt -p "Session label:" "run-shell '$HOME/bin/domux label --session \"#{session_name}\" set \"%%\"'"
bind-key n run-shell '$HOME/bin/domux label --session "#{session_name}" clear' \; display-message "domux label cleared"

set-option -g status-right '#($HOME/bin/domux status "#{session_name}" "#{pane_current_path}") #[fg=#{@tertiary-bg},bg=#{status-bg}]#[fg=#{status-fg},bg=#{@tertiary-bg}] %H:%M #[fg=#{@tertiary-bg},bg=#{status-bg}] #[fg=#{@quaternary-bg},bg=#{status-bg}]#[fg=#{status-fg},bg=#{@quaternary-bg}] %d-%b-%y   '
`) + "\n"
}

func installClaude(args []string) error {
	fs := flag.NewFlagSet("install claude", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	apply := fs.Bool("apply", false, "patch ~/.claude/settings.json")
	if err := fs.Parse(args); err != nil {
		return err
	}
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot get home directory: %w", err)
	}
	path := filepath.Join(homeDir, ".claude", "settings.json")
	next, err := patchedClaudeSettings(path)
	if err != nil {
		return err
	}
	cmdPath := filepath.Join(homeDir, ".claude", "commands", claudeStartTaskFile)
	if !*apply {
		data, _ := json.MarshalIndent(next, "", "  ")
		fmt.Printf("Would patch %s with domux hooks/statusLine:\n\n%s\n", path, data)
		fmt.Printf("\nWould write %s (the /start-task slash command).\n", cmdPath)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("cannot create %s: %w", filepath.Dir(path), err)
	}
	if err := backupIfExists(path); err != nil {
		return err
	}
	data, err := json.MarshalIndent(next, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	if err := os.WriteFile(path, data, 0600); err != nil {
		return fmt.Errorf("cannot write %s: %w", path, err)
	}
	fmt.Printf("patched %s\n", path)
	if err := writeClaudeCommand(cmdPath, claudeStartTaskCommand); err != nil {
		return err
	}
	return nil
}

func writeClaudeCommand(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("cannot create %s: %w", filepath.Dir(path), err)
	}
	existing, err := os.ReadFile(path)
	if err == nil && string(existing) == content {
		return nil
	}
	if err == nil {
		if err := backupIfExists(path); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("cannot read %s: %w", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("cannot write %s: %w", path, err)
	}
	fmt.Printf("wrote %s\n", path)
	return nil
}

func patchedClaudeSettings(path string) (map[string]any, error) {
	settings := map[string]any{}
	data, err := os.ReadFile(path)
	if err == nil && len(strings.TrimSpace(string(data))) > 0 {
		if err := json.Unmarshal(data, &settings); err != nil {
			return nil, fmt.Errorf("cannot parse %s: %w", path, err)
		}
	} else if err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("cannot read %s: %w", path, err)
	}

	hooks, _ := settings["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
		settings["hooks"] = hooks
	}
	addCommandHook(hooks, "SessionStart", "", "domux workspace occupied")
	addCommandHook(hooks, "SessionEnd", "", "domux workspace free && domux ai-state clear")
	addCommandHook(hooks, "PreToolUse", "*", "domux ai-state CLAUDING")
	addCommandHook(hooks, "UserPromptSubmit", "", "domux ai-state CLAUDING")
	addCommandHook(hooks, "Notification", "", "domux ai-state WAITING")
	addCommandHook(hooks, "PreCompact", "", "domux ai-state --agent claude COMPACTING")
	addCommandHook(hooks, "PostCompact", "", "domux ai-state --agent claude CLAUDING")
	addCommandHook(hooks, "Stop", "", "domux ai-state clear")

	// Only set statusLine if the user hasn't configured one. Overwriting
	// a custom statusLine (custom shell script, etc.) without warning is
	// the kind of side effect that doesn't belong in an idempotent patch.
	if _, exists := settings["statusLine"]; !exists {
		settings["statusLine"] = map[string]any{
			"type":    "command",
			"command": "domux claude-statusline",
		}
	}
	return settings, nil
}

func installCodex(args []string) error {
	fs := flag.NewFlagSet("install codex", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	apply := fs.Bool("apply", false, "patch ~/.codex/hooks.json")
	if err := fs.Parse(args); err != nil {
		return err
	}
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot get home directory: %w", err)
	}
	path := filepath.Join(homeDir, ".codex", "hooks.json")
	hooks := map[string]any{}
	data, err := os.ReadFile(path)
	if err == nil && len(strings.TrimSpace(string(data))) > 0 {
		if err := json.Unmarshal(data, &hooks); err != nil {
			return fmt.Errorf("cannot parse %s: %w", path, err)
		}
	} else if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("cannot read %s: %w", path, err)
	}

	next := patchedCodexHooks(hooks)
	if !*apply {
		data, _ := json.MarshalIndent(next, "", "  ")
		fmt.Printf("Would patch %s with domux hooks:\n\n%s\n", path, data)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("cannot create %s: %w", filepath.Dir(path), err)
	}
	if err := backupIfExists(path); err != nil {
		return err
	}
	data, err = json.MarshalIndent(next, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	if err := os.WriteFile(path, data, 0600); err != nil {
		return fmt.Errorf("cannot write %s: %w", path, err)
	}
	fmt.Printf("patched %s\n", path)
	return nil
}

func patchedCodexHooks(settings map[string]any) map[string]any {
	if settings == nil {
		settings = map[string]any{}
	}
	hooks, _ := settings["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
		settings["hooks"] = hooks
	}
	pruneCopiedClaudeCodexHooks(hooks)
	addCommandHook(hooks, "UserPromptSubmit", "", codexDomuxHook("ai-state --agent codex CODEXING"))
	addCommandHook(hooks, "PreToolUse", "*", codexDomuxHook("ai-state --agent codex CODEXING"))
	addCommandHook(hooks, "PostToolUse", "*", codexDomuxHook("ai-state --agent codex CODEXING"))
	addCommandHook(hooks, "PermissionRequest", "*", codexDomuxHook("ai-state --agent codex WAITING"))
	addCommandHook(hooks, "Stop", "", codexDomuxHook("ai-state --agent codex --all clear"))
	return settings
}

func codexDomuxHook(args string) string {
	homeDir, err := os.UserHomeDir()
	if err != nil || homeDir == "" {
		return "domux " + args
	}
	return shellCommandPath(filepath.Join(homeDir, "bin", "domux")) + " " + args
}

func shellCommandPath(path string) string {
	if !strings.ContainsAny(path, " \t\n'\"\\$`!*?[]{}()<>|&;") {
		return path
	}
	return "'" + strings.ReplaceAll(path, "'", "'\\''") + "'"
}

func pruneCopiedClaudeCodexHooks(hooks map[string]any) {
	for event, rawEntries := range hooks {
		entries, ok := rawEntries.([]any)
		if !ok {
			continue
		}
		nextEntries := make([]any, 0, len(entries))
		for _, rawEntry := range entries {
			entry, ok := rawEntry.(map[string]any)
			if !ok {
				nextEntries = append(nextEntries, rawEntry)
				continue
			}
			rawHookList, _ := entry["hooks"].([]any)
			nextHookList := make([]any, 0, len(rawHookList))
			for _, rawHook := range rawHookList {
				hook, ok := rawHook.(map[string]any)
				if !ok {
					nextHookList = append(nextHookList, rawHook)
					continue
				}
				command, _ := hook["command"].(string)
				if isCopiedClaudeCodexHook(command) {
					continue
				}
				nextHookList = append(nextHookList, rawHook)
			}
			if len(nextHookList) == 0 {
				continue
			}
			entry["hooks"] = nextHookList
			nextEntries = append(nextEntries, entry)
		}
		if len(nextEntries) == 0 {
			delete(hooks, event)
		} else {
			hooks[event] = nextEntries
		}
	}
}

func isCopiedClaudeCodexHook(command string) bool {
	return strings.Contains(command, ".tmux-claude-") ||
		strings.Contains(command, ".tmux-workspace-$(tmux display-message") ||
		command == "domux workspace occupied" ||
		strings.Contains(command, `"$HOME/bin/domux" ai-state --agent codex`) ||
		command == "domux ai-state --agent codex CODEXING" ||
		command == "domux ai-state --agent codex WAITING" ||
		command == "domux ai-state --agent codex --all clear" ||
		command == "domux ai-state --agent codex clear"
}

func addCommandHook(hooks map[string]any, event, matcher, command string) {
	existing, _ := hooks[event].([]any)
	if hookCommandExists(existing, command) {
		return
	}
	entry := map[string]any{
		"hooks": []any{
			map[string]any{
				"type":    "command",
				"command": command,
			},
		},
	}
	if matcher != "" {
		entry["matcher"] = matcher
	}
	hooks[event] = append(existing, entry)
}

func hookCommandExists(entries []any, command string) bool {
	for _, entry := range entries {
		entryMap, ok := entry.(map[string]any)
		if !ok {
			continue
		}
		hooks, _ := entryMap["hooks"].([]any)
		for _, hook := range hooks {
			hookMap, ok := hook.(map[string]any)
			if !ok {
				continue
			}
			if hookMap["command"] == command {
				return true
			}
		}
	}
	return false
}

func backupIfExists(path string) error {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return fmt.Errorf("cannot stat %s: %w", path, err)
	}
	backup := fmt.Sprintf("%s.domux-backup-%s", path, time.Now().Format("20060102150405"))
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("cannot read %s: %w", path, err)
	}
	if err := os.WriteFile(backup, data, 0600); err != nil {
		return fmt.Errorf("cannot write backup %s: %w", backup, err)
	}
	return nil
}

func doctorCommand(args []string) error {
	if len(args) != 0 {
		return fmt.Errorf("doctor does not accept arguments")
	}
	checks := []struct {
		Name string
		OK   bool
		Info string
	}{
		{Name: "tmux", OK: commandExists("tmux"), Info: "tmux binary on PATH"},
		{Name: "domux", OK: commandExists("domux"), Info: "domux binary on PATH"},
	}
	dataDir, err := domuxDataDir()
	checks = append(checks, checkResult("data dir", err == nil && dirExists(dataDir), dataDir))
	configDir, err := domuxConfigDir()
	checks = append(checks, checkResult("config dir", err == nil && dirExists(configDir), configDir))
	tmuxFile, err := domuxConfigDir("domux.tmux")
	checks = append(checks, checkResult("tmux integration", err == nil && fileExists(tmuxFile), tmuxFile))
	homeDir, _ := os.UserHomeDir()
	claudeSettings := filepath.Join(homeDir, ".claude", "settings.json")
	checks = append(checks, checkResult("Claude settings", fileExists(claudeSettings), claudeSettings))
	codexHooks := filepath.Join(homeDir, ".codex", "hooks.json")
	checks = append(checks, checkResult("Codex hooks", fileExists(codexHooks), codexHooks))
	caffPath, err := caffeinateConfigPath()
	checks = append(checks, checkResult("caffeinate", err == nil && fileExists(caffPath), caffPath))

	for _, check := range checks {
		mark := "ok"
		if !check.OK {
			mark = "missing"
		}
		fmt.Printf("%-18s %-8s %s\n", check.Name, mark, check.Info)
	}
	return nil
}

func checkResult(name string, ok bool, info string) struct {
	Name string
	OK   bool
	Info string
} {
	return struct {
		Name string
		OK   bool
		Info string
	}{Name: name, OK: ok, Info: info}
}

func migrateCommand(args []string) error {
	fs := flag.NewFlagSet("migrate", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	apply := fs.Bool("apply", false, "write domux session registry entries")
	if err := fs.Parse(args); err != nil {
		return err
	}
	sessions, err := currentTmuxSessions()
	if err != nil {
		return err
	}
	if len(sessions) == 0 {
		fmt.Println("no tmux sessions found")
		return nil
	}
	for _, session := range sessions {
		path, _ := tmuxPanePath(session)
		root := path
		if path != "" {
			if resolved, err := resolveRoot(path); err == nil {
				root = resolved
			}
		}
		if !*apply {
			fmt.Printf("would adopt %-20s %s\n", session, root)
			continue
		}
		if root == "" {
			continue
		}
		if _, err := setSessionRoot(session, root); err != nil {
			return err
		}
		fmt.Printf("adopted %-20s %s\n", session, root)
	}
	return nil
}

func claudeStatuslineCommand(args []string) error {
	if len(args) != 0 {
		return fmt.Errorf("claude-statusline does not accept arguments")
	}
	input, err := io.ReadAll(os.Stdin)
	if err != nil {
		return err
	}
	var payload map[string]any
	_ = json.Unmarshal(input, &payload)
	cwd := nestedString(payload, "workspace", "current_dir")
	if cwd == "" {
		cwd = stringValue(payload["cwd"])
	}
	if cwd == "" {
		cwd, _ = os.Getwd()
	}
	dirName := filepath.Base(cwd)
	model := nestedString(payload, "model", "display_name")
	model = strings.TrimPrefix(model, "Claude ")
	branch := gitBranch(cwd)
	if branch != "" {
		branch = " on \033[35m" + branch + "\033[0m"
	}
	if model != "" {
		fmt.Printf("\033[36m%s\033[0m%s \033[2m(%s)\033[0m\n", dirName, branch, model)
		return nil
	}
	fmt.Printf("\033[36m%s\033[0m%s\n", dirName, branch)
	return nil
}

func currentTmuxSessions() ([]string, error) {
	out, err := exec.Command("tmux", "list-sessions", "-F", "#{session_name}").CombinedOutput()
	if err != nil {
		msg := strings.TrimSpace(string(out))
		if msg == "" || strings.Contains(msg, "no server") || strings.Contains(msg, "failed to connect") {
			return nil, nil
		}
		return nil, fmt.Errorf("tmux list-sessions: %w: %s", err, msg)
	}
	var sessions []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if strings.TrimSpace(line) != "" {
			sessions = append(sessions, strings.TrimSpace(line))
		}
	}
	sort.Strings(sessions)
	return sessions, nil
}

func tmuxPanePath(session string) (string, error) {
	out, err := exec.Command("tmux", "display-message", "-t", session, "-p", "#{pane_current_path}").Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

func commandExists(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func nestedString(payload map[string]any, keys ...string) string {
	var current any = payload
	for _, key := range keys {
		m, ok := current.(map[string]any)
		if !ok {
			return ""
		}
		current = m[key]
	}
	return stringValue(current)
}

func stringValue(value any) string {
	if s, ok := value.(string); ok {
		return s
	}
	return ""
}

func gitBranch(dir string) string {
	cmd := exec.Command("git", "-C", dir, "branch", "--show-current")
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
